Azure DevOps template added

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -19,6 +19,19 @@ runs:
         if [ ! -f /usr/local/bin/datadog-ci ]; then
           curl -L --fail "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-x64" --output "/usr/local/bin/datadog-ci" && chmod +x /usr/local/bin/datadog-ci
         fi
+        if ! which datadog-ci > /dev/null 2>&1; then
+          echo "Datadog CI is not installed. Proceeding with installation..."
+          curl -L --fail "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-x64" --output "/usr/local/bin/datadog-ci" && chmod +x /usr/local/bin/datadog-ci
+    
+          if [ $? -eq 0 ]; then
+            echo "Datadog CI has been successfully installed."
+          else
+            echo "Failed to install Datadog CI. Please check your installation process."
+            exit 1
+          fi
+        else
+          echo "Datadog CI is already installed."
+        fi
       shell: bash
     
     - name: Assume AWS management account role
