Initial action added

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -26,25 +26,28 @@ runs:
       continue-on-error: true
       run: |
         export DD_API_KEY=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-west-1:865076270365:secret:DatadogGithubActionsApiKey-prGZpR --query SecretString --output text)
+        
+        export NODE_OPTIONS_BACKUP=$NODE_OPTIONS
+        export NODE_OPTIONS=""
+        unset NODE_OPTIONS
 
         if ! which datadog-ci > /dev/null 2>&1; then
-          echo "Datadog CI is not installed. Proceeding with installation..."
-          if curl -L --fail "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-x64" --output "/usr/local/bin/datadog-ci" && chmod +x /usr/local/bin/datadog-ci; then
-            echo "Datadog CI has been successfully installed."
-          else
-            echo "Failed to install Datadog CI. Please check your installation process."
-            exit 0
-          fi
+              echo "Datadog CI is not installed. Proceeding with installation..."
+              if curl -L --fail "https://github.com/DataDog/datadog-ci/releases/latest/download/datadog-ci_linux-x64" --output "/usr/local/bin/datadog-ci"; then
+                chmod +x /usr/local/bin/datadog-ci
+                echo "Datadog CI has been successfully installed."
+
+                /usr/local/bin/datadog-ci ${{ inputs.COMMAND }}
+              else
+                echo "Failed to install Datadog CI. Please check your installation process."
+                exit 1
+              fi
         else
-          echo "Datadog CI is already installed."
+              echo "Datadog CI is already installed."
+              datadog-ci ${{ inputs.COMMAND }}
         fi
 
-        if which datadog-ci > /dev/null 2>&1; then
-          datadog-ci ${{ inputs.COMMAND }}"
-        else
-          echo "Datadog CI is not installed. Skipping execution of command."
-          exit 0
-        fi
+        export NODE_OPTIONS=$NODE_OPTIONS_BACKUP
         unset DD_API_KEY
       shell: bash
       env:
